config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :bank_details
  get 'dashboard/index'
  resources :categories
  
  root to:'clients#index'
  devise_for :users

  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'
  resources :clients do
    resources :invoices
  end

  resources :projects
  resources :tasks
  get 'say/hello'
  get 'say/goodbye'
  get 'say/data'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

       
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/bank_detail.rb
class BankDetail < ActiveRecord::Base
	belongs_to :client
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :project_categories
	has_many :project, through: :project_categories
end

app/models/client.rb
class Client < ActiveRecord::Base
	acts_as_paranoid

	has_many:projects, dependent: :destroy
	belongs_to:user
	has_one :bank_detail
	has_many :invoices
	accepts_nested_attributes_for :bank_detail #depend on association
	

validates_presence_of :name,:email
validates_length_of :name,minimum:3,maximum:20
validates_numericality_of :mobile
validates_length_of :mobile, is:10
validates_uniqueness_of :email
validates_format_of:email,with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

def list_projects
		Project.where('client_id =?', self.id)
end
def open_projects
	Project.where('client_id = ? AND status = ?',self.id,"open")    #its called on client object which is retrieved

end
def completed_projects
	Project.where('client_id = ? AND status = ?',self.id,"completed")
end


end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	belongs_to :client

	def details 
		"#{invoice_date}"
	end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :role
	belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to:user
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :client
	has_many:tasks
	belongs_to:user

	has_many :project_categories
	has_many :categories, through: :project_categories

	#arguments will have a colon before
	#method options will have a colon after
	#option values will have colon before
     validates_presence_of :name,:status
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
	belongs_to :project
	belongs_to :category
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :permissions
	has_many :users, through: :permissions
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to:project
	belongs_to:user

	validates :name, presence: true
	validate :check_due_date

	private 

	def check_due_date
      if !self.due_date.nil? && self.due_date <self.project.start_date
      	errors.add(:due_date,"is invalid. cannot be less than #{self.project.start_date}")
       end
	end

end
 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :profile
	has_many :clients
	has_many :projects
	has_many :tasks

	has_many :permissions
	has_many :roles, through: :permissions
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @client = Client.find(params[:client_id])
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
     @client = Client.find(params[:client_id])
  end

  # POST /invoices
  # POST /invoices.json
  def create
     @client = Client.find(params[:client_id])
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:invoice_date, :client_id, :amount)
    end
end

app/controllers/say_controller.rb
class SayController < ApplicationController  #say is the controller and hello is the action (method)
  def hello

  	@clients = Client.all
  end
    
    def data
    	@clients = Client.all
    	@projects = Project.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Taskbox"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/bank_details_helper.rb
module BankDetailsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/invoices/_form.html.erb
<%= form_for([@client,@invoice]) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :invoice_date %><br>
    <%= f.date_select :invoice_date %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= @client.name %>
   <%= f.hidden_field :client_id, value: @client.id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Invoice date</th>
      <th>Client</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.invoice_date %></td>
        <td><%= invoice.client_id %></td>
        <td><%= invoice.amount %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Invoice date:</strong>
  <%= @invoice.invoice_date %>
</p>

<p>
  <strong>Client:</strong>
  <%= @invoice.client_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @invoice.amount %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>