config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :bank_details
  get 'dashboard/index'
  resources :categories
  
  root to:'clients#index'
  devise_for :users

  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'
  resources :clients do
    resources :invoices
  end

  resources :projects
  resources :tasks
  get 'say/hello'
  get 'say/goodbye'
  get 'say/data'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

       
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/bank_detail.rb
class BankDetail < ActiveRecord::Base
	belongs_to :client
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :project_categories
	has_many :project, through: :project_categories
end

app/models/client.rb
class Client < ActiveRecord::Base
	acts_as_paranoid

	has_many:projects, dependent: :destroy
	belongs_to:user
	has_one :bank_detail
	has_many :invoices
	accepts_nested_attributes_for :bank_detail #depend on association
	

validates_presence_of :name,:email
validates_length_of :name,minimum:3,maximum:20
validates_numericality_of :mobile
validates_length_of :mobile, is:10
validates_uniqueness_of :email
validates_format_of:email,with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

def list_projects
		Project.where('client_id =?', self.id)
end
def open_projects
	Project.where('client_id = ? AND status = ?',self.id,"open")    #its called on client object which is retrieved

end
def completed_projects
	Project.where('client_id = ? AND status = ?',self.id,"completed")
end


end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	belongs_to :client

	def details 
		"#{invoice_date}"
	end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :role
	belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to:user
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :client
	has_many:tasks
	belongs_to:user

	has_many :project_categories
	has_many :categories, through: :project_categories

	#arguments will have a colon before
	#method options will have a colon after
	#option values will have colon before
     validates_presence_of :name,:status
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
	belongs_to :project
	belongs_to :category
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :permissions
	has_many :users, through: :permissions
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to:project
	belongs_to:user

	validates :name, presence: true
	validate :check_due_date

	private 

	def check_due_date
      if !self.due_date.nil? && self.due_date <self.project.start_date
      	errors.add(:due_date,"is invalid. cannot be less than #{self.project.start_date}")
       end
	end

end
 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :profile
	has_many :clients
	has_many :projects
	has_many :tasks

	has_many :permissions
	has_many :roles, through: :permissions
end

app/controllers/bank_details_controller.rb
class BankDetailsController < ApplicationController
  before_action :set_bank_detail, only: [:show, :edit, :update, :destroy]

  # GET /bank_details
  # GET /bank_details.json
  def index
    @bank_details = BankDetail.all
  end

  # GET /bank_details/1
  # GET /bank_details/1.json
  def show
  end

  # GET /bank_details/new
  def new
    @bank_detail = BankDetail.new
  end

  # GET /bank_details/1/edit
  def edit
  end

  # POST /bank_details
  # POST /bank_details.json
  def create
    @bank_detail = BankDetail.new(bank_detail_params)

    respond_to do |format|
      if @bank_detail.save
        format.html { redirect_to @bank_detail, notice: 'Bank detail was successfully created.' }
        format.json { render :show, status: :created, location: @bank_detail }
      else
        format.html { render :new }
        format.json { render json: @bank_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_details/1
  # PATCH/PUT /bank_details/1.json
  def update
    respond_to do |format|
      if @bank_detail.update(bank_detail_params)
        format.html { redirect_to @bank_detail, notice: 'Bank detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_detail }
      else
        format.html { render :edit }
        format.json { render json: @bank_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_details/1
  # DELETE /bank_details/1.json
  def destroy
    @bank_detail.destroy
    respond_to do |format|
      format.html { redirect_to bank_details_url, notice: 'Bank detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_detail
      @bank_detail = BankDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_detail_params
      params.require(:bank_detail).permit(:client_id, :acc_no, :bank_name, :tin_number)
    end
end

app/controllers/say_controller.rb
class SayController < ApplicationController  #say is the controller and hello is the action (method)
  def hello

  	@clients = Client.all
  end
    
    def data
    	@clients = Client.all
    	@projects = Project.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Taskbox"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/bank_details_helper.rb
module BankDetailsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/bank_details/_form.html.erb
<%= form_for(@bank_detail) do |f| %>
  <% if @bank_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank_detail.errors.count, "error") %> prohibited this bank_detail from being saved:</h2>

      <ul>
      <% @bank_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :acc_no %><br>
    <%= f.text_field :acc_no %>
  </div>
  <div class="field">
    <%= f.label :bank_name %><br>
    <%= f.text_field :bank_name %>
  </div>
  <div class="field">
    <%= f.label :tin_number %><br>
    <%= f.text_field :tin_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bank_details/edit.html.erb
<h1>Editing Bank Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank_detail %> |
<%= link_to 'Back', bank_details_path %>

app/views/bank_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bank Details</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Acc no</th>
      <th>Bank name</th>
      <th>Tin number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bank_details.each do |bank_detail| %>
      <tr>
        <td><%= bank_detail.client_id %></td>
        <td><%= bank_detail.acc_no %></td>
        <td><%= bank_detail.bank_name %></td>
        <td><%= bank_detail.tin_number %></td>
        <td><%= link_to 'Show', bank_detail %></td>
        <td><%= link_to 'Edit', edit_bank_detail_path(bank_detail) %></td>
        <td><%= link_to 'Destroy', bank_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank detail', new_bank_detail_path %>

app/views/bank_details/new.html.erb
<h1>New Bank Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', bank_details_path %>

app/views/bank_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @bank_detail.client_id %>
</p>

<p>
  <strong>Acc no:</strong>
  <%= @bank_detail.acc_no %>
</p>

<p>
  <strong>Bank name:</strong>
  <%= @bank_detail.bank_name %>
</p>

<p>
  <strong>Tin number:</strong>
  <%= @bank_detail.tin_number %>
</p>

<%= link_to 'Edit', edit_bank_detail_path(@bank_detail) %> |
<%= link_to 'Back', bank_details_path %>