config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :bank_details
  get 'dashboard/index'
  resources :categories
  
  root to:'clients#index'
  devise_for :users

  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'
  resources :clients do
    resources :invoices
  end

  resources :projects
  resources :tasks
  get 'say/hello'
  get 'say/goodbye'
  get 'say/data'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

       
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/bank_detail.rb
class BankDetail < ActiveRecord::Base
	belongs_to :client
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :project_categories
	has_many :project, through: :project_categories
end

app/models/client.rb
class Client < ActiveRecord::Base
	acts_as_paranoid

	has_many:projects, dependent: :destroy
	belongs_to:user
	has_one :bank_detail
	has_many :invoices
	accepts_nested_attributes_for :bank_detail #depend on association
	

validates_presence_of :name,:email
validates_length_of :name,minimum:3,maximum:20
validates_numericality_of :mobile
validates_length_of :mobile, is:10
validates_uniqueness_of :email
validates_format_of:email,with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

def list_projects
		Project.where('client_id =?', self.id)
end
def open_projects
	Project.where('client_id = ? AND status = ?',self.id,"open")    #its called on client object which is retrieved

end
def completed_projects
	Project.where('client_id = ? AND status = ?',self.id,"completed")
end


end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	belongs_to :client

	def details 
		"#{invoice_date}"
	end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :role
	belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to:user
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :client
	has_many:tasks
	belongs_to:user

	has_many :project_categories
	has_many :categories, through: :project_categories

	#arguments will have a colon before
	#method options will have a colon after
	#option values will have colon before
     validates_presence_of :name,:status
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
	belongs_to :project
	belongs_to :category
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :permissions
	has_many :users, through: :permissions
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to:project
	belongs_to:user

	validates :name, presence: true
	validate :check_due_date

	private 

	def check_due_date
      if !self.due_date.nil? && self.due_date <self.project.start_date
      	errors.add(:due_date,"is invalid. cannot be less than #{self.project.start_date}")
       end
	end

end
 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :profile
	has_many :clients
	has_many :projects
	has_many :tasks

	has_many :permissions
	has_many :roles, through: :permissions
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
before_filter :authenticate_user!

def index
         @clients = current_user.is_admin ? Client.all : current_user.clients
end

def new 
        @client= Client.new
        @bank_detail = @client.build_bank_detail
end

def create 
	@client = Client.new(client_params)
	@client.user_id = current_user.id
	if @client.save
		redirect_to clients_path, notice: "suceessfully created the client"
	else
	   render "new"
	end
end

def show

	begin
     @client = current_user.clients.find(params[:id])
 rescue ActiveRecord::RecordNotFound
 	redirect_to clients_path, notice: "Record Not Found"
 	end
 	#respond_to do |format|
    #format.html
    #format.json { render json: @client,root: false} 
#end
 
end

def edit 
	begin
  @client = Client.find(params[:id])
  rescue ActiveRecord::RecordNotFound
 	redirect_to clients_path, notice: "Record Not Found"
 end
     @bank_detail =@client.bank_detail.nil? ? @client.build_bank_detail : @client_bank_detail
end

def update 
@client = Client.find(params[:id])
if @client.update_attributes(client_params)
	redirect_to client_path(@client.id), notice:"suceessfully updated the client"
else 
	render "edit"

end
end
def destroy
   @client = Client.find(params[:id])
   @client.destroy
   redirect_to clients_path, notice:"suceessfully deleted the client"
end

private
def client_params
	params[:client].permit(:name, :company, :website, :email, :mobile,bank_detail_attributes: [:acc_no, :bank_name, :tin_number])
end
end

app/controllers/say_controller.rb
class SayController < ApplicationController  #say is the controller and hello is the action (method)
  def hello

  	@clients = Client.all
  end
    
    def data
    	@clients = Client.all
    	@projects = Project.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Taskbox"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/bank_details_helper.rb
module BankDetailsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/clients/_form.html.erb


<%= form_for @client do |f| %>

<% if @client.errors.any? %>
<div class="errors" style="color:red" %>
<ul>
<% for msg in @client.errors.full_messages %>
<li> <%=msg%> </li>
<%end %>
</ul>
</div>
<%end%>

	<label> Name </label> <br/>
	<%= f.text_field :name %> <br/>
	
    <label> Company </label> <br/>
	<%= f.text_field :company %> <br/>
	
	<label> Website </label> <br/>
	<%= f.text_field :website %> <br/>

	<label> Email </label> <br/>
	<%= f.email_field :email %> <br/>

	<label> Mobile </label> <br/>
	<%= f.text_field :mobile%> <br/>

     <%= f.fields_for :bank_detail do |bank| %>  <!-- bank_Detail :model -->
        <div class="field">
        <label>Account No </label> <br/>
        <%= bank.text_field :acc_no %>
        </div>
        <div class="field">
        <label>Bank name </label> <br/>
        <%= bank.text_field :bank_name%>
        </div>
        <div class="field">
        <label>Tin num</label> <br/>
        <%= bank.text_field :tin_number %>
        </div>
        <% end%>
	<%=f.submit "Submit" ,class: 'btn btn-primary'%>
	<%end%>

app/views/clients/_table.html.erb
<script type="text/javascript">
$(document).ready(function(){
    $('#myTable').DataTable();
});

</script>

<div class="table-responsive">
  	<table border="1" id="myTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
<thead>
   <tr>
  	    <th> #</th>
  	    <th> Name </th>
  	    <th> Company</th>
  	    <th> No of projects</th>
        </tr>
         </thead>

       <% @clients.each_with_index do |client,index| %>
        <tr>
          <td><%= index + 1%></td>
          <td><%=  link_to client.name, client_path(client.id) %> </td>  <!-- client_path with id for show action-->
          <td><%= client.company %> </td>
          
          <td><%= client.projects.size %></td>
        </tr>
        <% end %>
        </table>
        </div>
     

app/views/clients/edit.html.erb
<% provide(:title, "Add Clients") %>
<div class="form">
<div class="container">
<div class="row">
<div class="col-md-12">
<h3> edit client </h3>
<%= render 'form' %>
	</div>
	</div>
	</div>
	</div>
	

app/views/clients/index.html.erb


	<% provide(:title, "Listing Clients") %>
	<div class="container-fluid">
  <h3 class="text-center"> Listing clients </h3>
  <%= link_to "Export to excel", clients_path(format:"xls") if current_user.is_admin? %>
 <div class="text-center">
	<strong> Total Clients = <%= @clients.size %> </strong>
  </div>
<%= render 'table' %>

<%= link_to "Add client" , new_client_path,class:'btn btn-info'%>
</div>

app/views/clients/index.xls.erb
<table border="1" id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
  	 <tr>
  	  <thead>
  	    <th> #</th>
  	    <th> Name </th>
  	    <th> Company</th>
  	    
  	    <th> No of projects</th>
       </thead>
       </tr>

       <% @clients.each_with_index do |client,index| %>
        <tr>
          <td><%= index + 1%></td>
          <td><%=  link_to client.name, client_url(client.id) %> </td>  <!-- client_path with id for show action-->
          <td><%= client.company %> </td>
          
          <td><%= client.projects.size %></td>
        </tr>
        <% end %>
        </table>

app/views/clients/new.html.erb

<h3> Add client </h3>
<div class="form-inline">

<%= render 'form' %>
	</div>
	 
 
   
   
	

app/views/clients/show.html.erb

  
  <div class="jumbotron">
  <h2><%= @client.name %>
  <small>
    <%= link_to "edit", edit_client_path(@client.id) %> | <%= link_to "destroy" ,client_path(@client.id), method: :delete,data: {
    	confirm: "Are you sure?"} %> <br/>
      <%= link_to "generate invoive" ,new_client_invoice_path(@client.id) %>
    </small>
   </h2>
  <div class="row">
  <div class="col-xs-6">
   <%= @client.mobile %>| <%=@client.website %> | <%=@client.company %>

    <% if @client.projects.empty? %>
     <p> No projects found. Add your first project <%= link_to "here" %>
     </p>
    <% else %>
      <h3>Project count =<%=@client.projects.size %> </h3>
      <ul>
      <% data ={} %>
      <% for project in @client.projects %>
      <li><%= project.name %> </li>
      
      <% end %>
      </ul>


      <%= column_chart(data) %>
      <% end %>
      <h3> Invoices sent </h3>
      <ul>
      <%for invoice in @client.invoices %>
      <li> <%= invoice.details %> <%= link_to "edit", edit_client_invoice_path(@client.id,invoice.id) %> </li>
      <% end %>
       <%= link_to "show clients", clients_path,class: 'btn btn-success'%>
      </div>
       </div>
      </div>