config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :bank_details
  get 'dashboard/index'
  resources :categories
  
  root to:'clients#index'
  devise_for :users

  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'
  resources :clients do
    resources :invoices
  end

  resources :projects
  resources :tasks
  get 'say/hello'
  get 'say/goodbye'
  get 'say/data'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

       
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/bank_detail.rb
class BankDetail < ActiveRecord::Base
	belongs_to :client
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :project_categories
	has_many :project, through: :project_categories
end

app/models/client.rb
class Client < ActiveRecord::Base
	acts_as_paranoid

	has_many:projects, dependent: :destroy
	belongs_to:user
	has_one :bank_detail
	has_many :invoices
	accepts_nested_attributes_for :bank_detail #depend on association
	

validates_presence_of :name,:email
validates_length_of :name,minimum:3,maximum:20
validates_numericality_of :mobile
validates_length_of :mobile, is:10
validates_uniqueness_of :email
validates_format_of:email,with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

def list_projects
		Project.where('client_id =?', self.id)
end
def open_projects
	Project.where('client_id = ? AND status = ?',self.id,"open")    #its called on client object which is retrieved

end
def completed_projects
	Project.where('client_id = ? AND status = ?',self.id,"completed")
end


end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	belongs_to :client

	def details 
		"#{invoice_date}"
	end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :role
	belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to:user
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :client
	has_many:tasks
	belongs_to:user

	has_many :project_categories
	has_many :categories, through: :project_categories

	#arguments will have a colon before
	#method options will have a colon after
	#option values will have colon before
     validates_presence_of :name,:status
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
	belongs_to :project
	belongs_to :category
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :permissions
	has_many :users, through: :permissions
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to:project
	belongs_to:user

	validates :name, presence: true
	validate :check_due_date

	private 

	def check_due_date
      if !self.due_date.nil? && self.due_date <self.project.start_date
      	errors.add(:due_date,"is invalid. cannot be less than #{self.project.start_date}")
       end
	end

end
 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :profile
	has_many :clients
	has_many :projects
	has_many :tasks

	has_many :permissions
	has_many :roles, through: :permissions
end

app/controllers/projects_controller.rb
 class ProjectsController < ApplicationController
     before_filter :authenticate_user!
    
   
        def index
        	if params[:client_id]
            @projects =current_user.projects.where('client_id=?',params[:client_id])
          else
            @projects =current_user.projects
          end

        end

        def new 
             @project=Project.new

        end

        def create
        	@project = Project.new(project_params)
	if @project.save
		redirect_to projects_path, notice: "suceessfully created the project"
	else
	   render "new"
	end

        end

        def show 
        @project = Project.find(params[:id])
        @task=Task.new
        end

        def edit 
    begin
      @project = Project.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to projects_path, notice: "Record Not Found"
     end
    end
    def update 
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
        redirect_to project_path(@project.id), notice:"suceessfully updated the project"
    else 
        render "edit"

    end
    end
    def destroy
       @project = Project.find(params[:id])
       @project.destroy
       redirect_to projects_path, notice:"suceessfully deleted the project"
    end
            private
    def project_params
    	params[:project].permit(:client_id,:name,:description,:start_date,:status)

    end 
    end

app/controllers/say_controller.rb
class SayController < ApplicationController  #say is the controller and hello is the action (method)
  def hello

  	@clients = Client.all
  end
    
    def data
    	@clients = Client.all
    	@projects = Project.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Taskbox"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/bank_details_helper.rb
module BankDetailsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/projects/edit.html.erb
<% provide(:title, "Edit Projects") %>
<div class="form">
<div class="container">
<div class="row">
<div class="col-md-12">
<h3> edit project </h3>
<%= form_for @project do |f| %>

<% if @project.errors.any? %>
<div class="errors" style="color:red" %>
<ul>
<% for msg in @project.errors.full_messages %>
<li> <%=msg%> </li>
<%end %>
</ul>
</div>
<%end%>

	<label> Client </label> <br/>
<%= f.collection_select :client_id, Client.all, :id, :company, prompt: "select" %> <br/>
<label> Name :</label> <br/>
<%=f.text_field :name, required:true %> </br>
<label> Description </label> <br/>
<%= f.text_area :description %> <br/>
<label> Start Date :</label> <br/>
<%=f.date_select :start_date, order:[:day,:month,:year] %> <br/>
<label> Status: </label> <br/>
<%=f.radio_button :status,"open" %> Open
<%=f.radio_button :status,"on-going" %> On-going
<%=f.radio_button :status,"completed" %> Completed
<br/>

	<%=f.submit "Submit" ,class: 'btn btn-primary'%>
	<%end%>
	</div>
	</div>
	</div>
	</div>
	

app/views/projects/index.html.erb
<h3 class="text-center"> Listing Projects </h3>
<strong> filter by :</strong>
<% for client in current_user.clients %>
<%= link_to client.name,projects_path(client_id: client.id) %> |
<% end %>
<table border="1" id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
<tr>
<thead>
  <th> Name </th>
  <th> Status </th>
  <th>Start_date </th>
  <th> Client </th>
</thead>
</tr>
<tbody>
  <% for project in @projects %>
  <tr>
    <td><%=link_to project.name, project_path(project.id) %> </td>
    <td><%= project.status %> </td>
    <td><%= project.start_date %> </td>
    <td><%= project.client.try(:name) %> </td>
    </tr>
    <% end %>
</tbody>
</table>


<%= link_to "Add project" , new_project_path , class:'btn btn-info'%>

app/views/projects/new.html.erb

<script>
  $(function() {
    $( "#datepicker" ).datepicker();
  });
  </script>
<h3> Add project </h3>

<%= form_for @project do |f| %>
	<label> Client </label> <br/>
<%= f.collection_select :client_id, Client.all, :id, :company, prompt: "select" %> <br/>
<label> Name :</label> <br/>
<%=f.text_field :name, required:true %> </br>
<label> Description </label> <br/>
<%= f.text_area :description %> <br/>
<label> Start Date :</label> <br/>
<%=f.text_field :start_date,id:'datepicker'%> <br/>
<label> Status: </label> <br/>
<%=f.radio_button :status,"open" %> Open
<%=f.radio_button :status,"on-going" %> On-going
<%=f.radio_button :status,"completed" %> Completed
<br/>
<%= f.submit %>


<%end%>

app/views/projects/show.html.erb

  <div class="jumbotron">
  <h2><%= @project.try(:name) %>
  <p> <%= @project.status %> | <%= @project.start_date.strftime("%A, %d %B %Y ") %> <br/>
  <small>
    <%= link_to "edit", edit_project_path(@project.id) %> | <%= link_to "destroy" ,project_path(@project.id), method: :delete,data: {
      confirm: "Are you sure?"} %>
    </small>

    <% data=[] %>

    <%for task in @project.tasks %>
        <% data.push([task.name,@project.start_date.to_s,task.due_date.to_s]) %>

    <%end %>

    <%= timeline(data) %>
  
     <h3> Client : </h3><%= link_to @project.client.try(:name), client_path(@project.client) %> <br/>
     <h3> Total Tasks :<%=@project.tasks.size %> </h3>
     <%over_due_tasks =@project.tasks.where('is_completed =? AND due_date <?',false,Date.today) %>
     <%incomplete_tasks =@project.tasks.where('is_completed =? AND due_date >=?',false,Date.today) %>
     <%completed_tasks =@project.tasks.where('is_completed =?',true) %>

      <h3> Overdue tasks </h3>
      <ul>
      <% for task in over_due_tasks %>
      <li> <%=task.name %> 
      <%= link_to "mark as complete", tasks_mark_as_complete_path(task_id: task.id) %> 
      </li>
      <%end%>
      </ul>
      <h3> Incomplete Tasks </h3>
      <% for task in incomplete_tasks %>
      <li> <%=task.name %> </li>
      <%end%>
      </ul>
      <h3> Completed tasks </h3>
      <% for task in completed_tasks %>
      <li> <%=task.name %> </li>
      <%= link_to "mark as incomplete", tasks_mark_as_incomplete_path(task_id: task.id) %>
      <%end%>
      </ul>



      <h3> Add Task </h3>
      <%=form_for @task do |f| %>
      <%= f.text_field :name,placeholder:"task name" %> <br/>
      <label> Due Date ? </label> <%=f.date_select :due_date %> <br/>
      <label> Is completed ?</label> <%=f.check_box:is_completed %> <br/>
      <%= f.hidden_field :project_id, value: @project.id %>
      <%= f.submit %>
      <%end%>
      </div>

       <%= link_to "show projects", projects_path,class: 'btn btn-info'%>
    
       </div>
      </div>